#!/usr/bin/env bash
#
# SecureBank Stage 1 <-> Stage 2 integration test
# ===============================================
# Proves the ecosystem claim: "Stage 1 is capable of observing traffic
# generated by Stage 2."
#
#   Kali (10.10.10.20)                  SecureBank server (10.10.10.10)
#     |  SSH / DNS / ICMP / HTTP  ---------->  (Stage 2 traffic generator)
#     |                                        |
#     |         both traverse the lab segment  |
#     +----------------------------------------+
#                        |
#                        v
#        Stage 1 analyzer (10.10.10.30) captures -> JSON report -> verified
#
# Run on the ANALYZER VM (10.10.10.30), as root or with capture permission:
#     sudo ./tests/integration_test.sh [interface]
#
# Prerequisites:
#   - lab.env at the repo root (clone the whole SecureBank-Enterprise-Lab)
#   - the Stage 2 traffic generator exists on Kali at
#     ~/SecureBank-Enterprise-Lab/stage2-securebank-linux-server
#     (override with SB_KALI_STAGE2_DIR; disable the trigger with
#     SB_SKIP_TRAFFIC_TRIGGER=1 and generate traffic manually)
#   - this VM can SSH to Kali as 'kali' with a key (override: SB_KALI_SSH_USER)
#
# Evidence is stored in reports/integration-<timestamp>/.

set -uo pipefail

STAGE1_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
REPO_DIR="$(cd "${STAGE1_DIR}/.." && pwd)"

LAB_ENV="${REPO_DIR}/lab.env"
if [ ! -f "${LAB_ENV}" ]; then
  echo "[integration][ERROR] Missing ${LAB_ENV} - clone the whole repo." >&2
  exit 1
fi
# shellcheck disable=SC1091
. "${LAB_ENV}"

IFACE="${1:-${SB_ANALYZER_IFACE:-eth0}}"
CAPTURE_SECS="${SB_CAPTURE_SECS:-25}"
ANALYZER="${STAGE1_DIR}/Project/outputs/network_traffic_analyzer.py"
KALI_USER="${SB_KALI_SSH_USER:-kali}"
KALI_STAGE2_DIR="${SB_KALI_STAGE2_DIR:-/root/SecureBank-Enterprise-Lab/stage2-securebank-linux-server}"

STAMP="$(date +%Y%m%d-%H%M%S)"
EVIDENCE="${STAGE1_DIR}/reports/integration-${STAMP}"
mkdir -p "${EVIDENCE}"
REPORT="${EVIDENCE}/traffic_report.json"

PASS=0
FAIL=0
ok()  { printf '\033[32m[PASS]\033[0m %s\n' "$1"; PASS=$((PASS + 1)); }
bad() { printf '\033[31m[FAIL]\033[0m %s\n' "$1"; FAIL=$((FAIL + 1)); }

echo "== SecureBank integration test: Stage 1 observes Stage 2 traffic =="
echo "   analyzer interface : ${IFACE}   (this VM: ${SB_ANALYZER_IP})"
echo "   traffic source     : ${KALI_USER}@${SB_KALI_IP} -> ${SB_SRV_IP}"

# --- Preconditions -------------------------------------------------------------
[ "$(id -u)" -eq 0 ] || { echo "[integration][ERROR] Run as root (sudo) - capture needs elevation." >&2; exit 1; }
command -v python3 >/dev/null || { echo "[integration][ERROR] python3 not found." >&2; exit 1; }
python3 -c "import scapy" 2>/dev/null || { echo "[integration][ERROR] scapy missing on the analyzer: python3 -m pip install scapy" >&2; exit 1; }

# --- 1. Start the capture ------------------------------------------------------
echo
echo "[integration] Capturing on ${IFACE} for ${CAPTURE_SECS}s (passive, metadata-only)..."
python3 "${ANALYZER}" --interface "${IFACE}" --timeout "${CAPTURE_SECS}" \
  --json-out "${REPORT}" > "${EVIDENCE}/capture.log" 2>&1 &
CAPTURE_PID=$!

# --- 2. Generate the controlled lab traffic (from Kali) -------------------------
sleep 3
if [ "${SB_SKIP_TRAFFIC_TRIGGER:-0}" = "1" ]; then
  echo "[integration] SB_SKIP_TRAFFIC_TRIGGER=1 - generate traffic manually within ${CAPTURE_SECS}s."
else
  echo "[integration] Triggering Stage 2 traffic generator on Kali (client mode)..."
  if ssh -o BatchMode=yes -o ConnectTimeout=5 -o StrictHostKeyChecking=accept-new \
      "${KALI_USER}@${SB_KALI_IP}" \
      "cd '${KALI_STAGE2_DIR}' && ./scripts/generate-lab-traffic.sh" \
      > "${EVIDENCE}/traffic-trigger.log" 2>&1; then
    ok "traffic generator ran on Kali (see reports/.../traffic-trigger.log)"
  else
    bad "traffic generator on Kali failed - see ${EVIDENCE}/traffic-trigger.log (run it manually and re-test)"
  fi
fi

# --- 3. Wait for the capture to finish ------------------------------------------
wait "${CAPTURE_PID}"
echo "[integration] Capture finished."

# --- 4/5. Verify the report -----------------------------------------------------
[ -f "${REPORT}" ] || { bad "no report produced (${REPORT})"; exit 1; }

python3 - "${REPORT}" "${SB_SRV_IP}" <<'PYEOF'
import json
import sys

report_path, server_ip = sys.argv[1], sys.argv[2]

def check(desc, cond):
    print(f"[{'PASS' if cond else 'FAIL'}] {desc}")
    if not cond:
        sys.exit(1)

with open(report_path, encoding="utf-8") as fh:
    report = json.load(fh)

check("report is valid JSON", True)
check("report carries schema_version", report.get("schema_version") == "traffic-report/1.0")
check("report has all required fields", all(
    k in report for k in ("generated_at", "packets", "bytes", "protocols",
                          "top_sources", "top_destinations", "top_flows",
                          "tcp_flags", "malformed_packets", "detections")))
check("captured packets > 0", report["packets"] > 0)
check("TCP observed (SSH)", report["protocols"].get("TCP", 0) > 0)
check("ICMP observed (ping)", report["protocols"].get("ICMP", 0) > 0)

addrs = {e["value"] for e in report["top_sources"]} | {e["value"] for e in report["top_destinations"]}
check(f"server {server_ip} seen in traffic", server_ip in addrs)

ssh_flows = [f for f in report["top_flows"] if f.get("dst_port") == "22" or f.get("src_port") == "22"]
check("SSH (port 22) flow recorded", len(ssh_flows) > 0)

print("\nReport: " + report_path)
PYEOF
PY_OK=$?

# --- 6. Store evidence ------------------------------------------------------------
{
  echo "Integration test evidence - $(date -u +%Y-%m-%dT%H:%M:%SZ)"
  echo "Analyzer: ${SB_ANALYZER_HOSTNAME}.${SB_DOMAIN} (${SB_ANALYZER_IP}) iface ${IFACE}"
  echo "Traffic : ${KALI_USER}@${SB_KALI_IP} -> ${SB_SRV_IP} (Stage 2 generator, client mode)"
  echo "Result  : $( [ "${PY_OK}" -eq 0 ] && echo PASS || echo FAIL )"
} > "${EVIDENCE}/summary.txt"

if [ "${PY_OK}" -eq 0 ]; then
  ok "Stage 1 observed Stage 2 traffic - evidence in reports/integration-${STAMP}/"
else
  bad "report verification failed - see reports/integration-${STAMP}/"
fi

echo
echo "Results: ${PASS} passed, ${FAIL} failed"
[ "${FAIL}" -eq 0 ] && [ "${PY_OK}" -eq 0 ]
